### ISSUE TITLE
yarn start fails on unreleased version

### ISSUE THREAD

**Issue by tibotiber** [tadatuta/rewire-entry#4]
Hi, I've installed from master the unreleased version. PR by @rsboarder. Prod build works but i'm getting some issue with starting the dev server (see below). Any idea?

```
❯ yarn start
yarn run v1.12.3
$ BROWSER='Google Chrome' react-app-rewired start
/Users/tibo/PTGEM/code/ptgem3D/frontend/node_modules/rewire-entry/src/index.js:86
      config.historyApiFallback.rewrites = bundles.slice(1).map(bundle => {
                                         ^

TypeError: Cannot set property 'rewrites' of undefined
    at Object.devServer (/Users/tibo/PTGEM/code/ptgem3D/frontend/node_modules/rewire-entry/src/index.js:86:42)
    at Object.devServer (/Users/tibo/PTGEM/code/ptgem3D/frontend/config-overrides.js:41:27)
    at Object.<anonymous> (/Users/tibo/PTGEM/code/ptgem3D/frontend/node_modules/react-app-rewired/scripts/start.js:25:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
error Command failed with exit code 1.
```

**Comment by tibotiber** [comment]
This has been inactive for a year and I do not work on the project that was affected anymore, so I figured I would close the issue. Cheers.
